### ISSUE TITLE
i am facing difficulty in installing the same on RHEL

### ISSUE THREAD

**Issue by ctr0306** [TritonDataCenter/triton#250]
1)
I have  a VM machine with 4 core, 32 GB RAM installing RHEL
Installed VM Workstation as you mentioned

2)
Then i tried running the below which is not required my understanding
curl -s https://raw.githubusercontent.com/joyent/sdc/master/tools/coal-linux-vmware-setup | sudo bash
It did not went fine gave errors

3)
tar -zxvf coal-latest.tgz -C ~/Documents/Virtual\ Machines.localized also did not went fine

could you please help here

**Comment by cypa** [comment]
to get help provide any error messages, please

**Comment by bahamat** [comment]
Triton only works on SmartOS, and only with the provided binary installer. See the "Getting Started" section of the README.

**Comment by bahamat** [comment]
Closing this because there's not enough detail.
